const scorers = [
    { name: "ARJUN", team: "FC REMONTADA", goals: 4 },
    { name: "SIDHARTHAN", team: "FC REMONTADA", goals: 1 },
    { name: "FAHEEM", team: "FC REMONTADA", goals: 3 },
    { name: "SINAN", team: "FC REMONTADA", goals: 3 },
    { name: "MISHEL", team: "SPORTING FC", goals: 4 },
    { name: "SONU", team: "SPORTING FC", goals: 2 },
    { name: "RASHID", team: "SPORTING FC", goals: 3 },
    { name: "AKHIL", team: "SPORTING FC", goals: 1 },
    { name: "SUJITH", team: "GUNNERS FC", goals: 1 },
    { name: "JAYANAND", team: "GUNNERS FC", goals: 1 },
    { name: "FALLAH", team: "GUNNERS FC", goals: 1 },
    { name: "SREEHARI", team: "CS UNITED", goals: 4 },
    { name: "JISHNU", team: "CS UNITED", goals: 4 },
    { name: "AKHIL P", team: "CS UNITED", goals: 1 },
    { name: "NANDHAKISHOR", team: "SHARTAAN FC", goals: 1 },
    { name: "AKHIL", team: "SHARTAAN FC", goals: 1 },
    { name: "SOORYAKIRAN", team: "TIHAR FC", goals: 1 },
    { name: "VIPIN", team: "TIHAR FC", goals: 1 },
    { name: "SHANIF", team: "CS UNITED", goals: 1 },
    { name: "RAGIN", team: "TIHAR FC", goals: 1 },
    { name: "NABEEL", team: "BATHAKKA FC", goals: 1 },
    { name: "ADEEB", team: "BATHAKKA FC", goals: 1 },
    { name: "SAHAJ", team: "BATHAKKA FC", goals: 2 },
    { name: "HILMI", team: "BATHAKKA FC", goals: 1 },
    { name: "HASHIM", team: "SANTOS FC", goals: 1 },
    { name: "YASEEN", team: "SANTOS FC", goals: 1 },
    { name: "MIRSHA", team: "SANTOS FC", goals: 1 },
  ];


  export default scorers;