const teams = [
  {
    name: "BATHAKKA FC",
    logo: "/logos/BATHAKKA FC.png",
    played: 5,
    wins: 1,
    draws: 3,
    losses: 1,
    goalsFor: 2,
    goalsAgainst: 3,
  },
  {
    name: "SPORTING FC",
    logo: "/logos/SPORTING FC.png",
    played: 6,
    wins: 3,
    draws: 3,
    losses: 0,
    goalsFor: 5,
    goalsAgainst: 1,
  },
  {
    name: "SANTOS FC",
    logo: "/logos/SANTOS FC.png",
    played: 5,
    wins: 1,
    draws: 1,
    losses: 3,
    goalsFor: 2,
    goalsAgainst: 3,
  },
  {
    name: "TIHAR FC",
    logo: "/logos/TIHAR FC.png",
    played: 6,
    wins: 0,
    draws: 2,
    losses: 4,
    goalsFor: 3,
    goalsAgainst: 10,
  },
  {
    name: "CS UNITED",
    logo: "/logos/CS-UNITED.png",
    played: 6,
    wins: 3,
    draws: 3,
    losses: 0,
    goalsFor: 8,
    goalsAgainst: 4,
  },
  {
    name: "FC REMONTADA",
    logo: "/logos/F C REMONTADA.png",
    played: 6,
    wins: 4,
    draws: 0,
    losses: 2,
    goalsFor: 8,
    goalsAgainst: 4,
  },
  {
    name: "GUNNERS FC",
    logo: "/logos/GUNNERS FC.png",
    played: 6,
    wins: 1,
    draws: 3,
    losses: 2,
    goalsFor: 1,
    goalsAgainst: 2,
  },
  {
    name: "SHARTAAN FC",
    logo: "/logos/SHARTAAN FC.png",
    played: 7,
    wins: 1,
    draws: 3,
    losses: 3,
    goalsFor: 2,
    goalsAgainst: 5,
  },
];

export default teams;
